[package]
name = "libxdpiface-sys"
version = "1.1.0"
links = "xdpiface"
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.53.1"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
