################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
NAME        = "xdpiface"
VERSION     = "1.1.0"
LICENSE     = "mit"
DESCRIPTION = """Python bindings of: project"""
URL         = "https://github.com/zeromq/xdpiface"
PACKAGES    = ["xdpiface"]
REQUIRES    = [
]
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
