/*  =========================================================================
    xdpiface - generated layer of public API

    MIT License

    Copyright (c) [2023] XDP Interface

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef XDPIFACE_LIBRARY_H_INCLUDED
#define XDPIFACE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies

//  XDPIFACE version macros for compile-time API detection
#define XDPIFACE_VERSION_MAJOR 1
#define XDPIFACE_VERSION_MINOR 1
#define XDPIFACE_VERSION_PATCH 0

#define XDPIFACE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define XDPIFACE_VERSION \
    XDPIFACE_MAKE_VERSION(XDPIFACE_VERSION_MAJOR, XDPIFACE_VERSION_MINOR, XDPIFACE_VERSION_PATCH)

// czmq_prelude.h bits
#if !defined (__WINDOWS__)
#   if (defined WIN32 || defined _WIN32 || defined WINDOWS || defined _WINDOWS)
#       undef __WINDOWS__
#       define __WINDOWS__
#   endif
#endif

// Windows MSVS doesn't have stdbool
#if (defined (_MSC_VER) && !defined (true))
#   if (!defined (__cplusplus) && (!defined (true)))
#       define true 1
#       define false 0
        typedef char bool;
#   endif
#else
#   include <stdbool.h>
#endif
// czmq_prelude.h bits

#if defined (__WINDOWS__)
#   if defined XDPIFACE_STATIC
#       define XDPIFACE_EXPORT
#   elif defined XDPIFACE_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define XDPIFACE_EXPORT __declspec(dllexport)
#       else
#           define XDPIFACE_EXPORT
#       endif
#   elif defined XDPIFACE_EXPORTS
#       define XDPIFACE_EXPORT __declspec(dllexport)
#   else
#       define XDPIFACE_EXPORT __declspec(dllimport)
#   endif
#   define XDPIFACE_PRIVATE
#elif defined (__CYGWIN__)
#   define XDPIFACE_EXPORT
#   define XDPIFACE_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define XDPIFACE_PRIVATE __attribute__ ((visibility ("hidden")))
#       define XDPIFACE_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define XDPIFACE_PRIVATE
#       define XDPIFACE_EXPORT
#   endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _xdp_iface_t xdp_iface_t;
#define XDP_IFACE_T_DEFINED
typedef struct _xdp_sock_t xdp_sock_t;
#define XDP_SOCK_T_DEFINED
#define XDP_LOG_T_DEFINED

//  Public classes, each with its own header file
#include "xdp_iface.h"
#include "xdp_sock.h"
#include "xdp_log.h"

#ifdef XDPIFACE_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
XDPIFACE_EXPORT void
    xdpiface_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // XDPIFACE_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
