name: Fedora Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fedora37_build_install:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Prepare runner
        working-directory: ./builds/vm/fedora
        run: sudo ./prepare_runner.sh

      - name: Cache VM disk
        working-directory: ./builds/vm/fedora
        id: cache-vm-disk
        run: |
          if [ -f ./f37vm.qcow2 ]; then
            echo "VM disk image found in cache"
          else
            echo "VM disk image not found in cache"
            sudo ./build_vm.sh
          fi

      - name: Grant permissions
        working-directory: ./builds/vm/fedora
        run: sudo setfacl -m u:libvirt-qemu:x /home/runner/

      - name: Install VM
        working-directory: ./builds/vm/fedora
        run: sudo ./install_vm.sh

      - name: Execute XDP iface selftest
        working-directory: ./builds/vm/fedora
        run: ./xdp_iface_test.sh
        continue-on-error: true

      - name: Save cache
        working-directory: ./builds/vm/fedora
        if: steps.cache-vm-disk.outputs.cache-hit != 'true'
        run: |
          echo "./f37vm.qcow2=${{ steps.cache-vm-disk.outputs.cache-hit }}" >> $GITHUB_ENV
