name: Fedora Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fedora37_build_install:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache QCOW VM
        uses: actions/cache@v3.0.5
        id: cache
        with:
          path: ./builds/vm/fedora/f37vm.qcow2
          key:  ${{ runner.os }}-qcow-cache

      - name: Prepare runner
        working-directory: ./builds/vm/fedora
        run: sudo ./prepare_runner.sh

      - name: Build VM
        working-directory: ./builds/vm/fedora
        run: sudo ./build_vm.sh

      - name: Grant permissions
        working-directory: ./builds/vm/fedora
        run: sudo setfacl -m u:libvirt-qemu:x /home/runner/

      - name: Install VM
        working-directory: ./builds/vm/fedora
        run: sudo ./install_vm.sh

      - name: Execute XDP iface selftest
        working-directory: ./builds/vm/fedora
        run: ./xdp_iface_test.sh
